# Install script for directory: /home/chris/cmake-2.3.4-20060317/Modules

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME Release)
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT CMAKE_INSTALL_CONFIG_NAME)

FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeBackwardCompatibilityC.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeBackwardCompatibilityCXX.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeBorlandFindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeCInformation.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeCXXInformation.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeCommonLanguageInclude.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeDetermineCCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeDetermineCXXCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeDetermineFortranCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeDetermineJavaCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeDetermineRCCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeDetermineSystem.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeExportBuildSettings.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeFindFrameworks.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeFindWMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeFindXCode.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeFortranInformation.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeGenericSystem.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeImportBuildSettings.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeJavaInformation.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeMSYSFindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeMinGWFindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeNMakeFindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakePrintSystemInformation.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeRCInformation.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeSystemSpecificInformation.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeTestCCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeTestCXXCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeTestFortranCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeTestJavaCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeTestRCCompiler.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeUnixFindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeVS6BackwardCompatibility.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeVS6FindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeVS71FindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeVS7BackwardCompatibility.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeVS7FindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeVS8FindMake.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CPack.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CTest.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CTestTargets.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckCSourceCompiles.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckCXXSourceCompiles.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckFunctionExists.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckIncludeFile.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckIncludeFileCXX.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckIncludeFiles.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckLibraryExists.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckSizeOf.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckSymbolExists.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckTypeSize.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckVariableExists.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/Dart.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/Documentation.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindAVIFile.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindCABLE.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindCurses.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindCygwin.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindDCMTK.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindDart.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindDoxygen.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindFLTK.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindGCCXML.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindGLU.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindGLUT.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindGTK.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindGnuplot.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindHTMLHelp.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindITK.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindImageMagick.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindJNI.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindJPEG.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindJava.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindKDE.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindKDE3.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindKDE4.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindLATEX.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindMFC.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindMPEG.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindMPEG2.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindMPI.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindMatlab.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindMotif.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindOpenAL.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindOpenGL.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindPHP4.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindPNG.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindPerl.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindPerlLibs.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindPhysFS.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindPike.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindPythonInterp.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindPythonLibs.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindQt.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindQt3.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindQt4.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindRuby.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindSDL.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindSDL_image.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindSDL_mixer.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindSDL_net.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindSDL_sound.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindSDL_ttf.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindSWIG.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindSelfPackers.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindTCL.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindTIFF.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindTclsh.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindThreads.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindUnixCommands.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindVTK.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindWget.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindWish.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindX11.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindZLIB.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindwxWidgets.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/FindwxWindows.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/InstallRequiredSystemLibraries.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/KDE3Macros.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestBigEndian.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestCXXAcceptsFlag.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestForANSIForScope.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestForANSIStreamHeaders.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestForSSTREAM.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestForSTDNamespace.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/UsePkgConfig.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/UseQt4.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/UseSWIG.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/UseVTK40.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/UseVTKBuildSettings40.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/UseVTKConfig40.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/Use_wxWindows.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/UsewxWidgets.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/VTKCompatibility.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/cmake_install.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/kde3uic.cmake")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeTestForFreeVC.cxx")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/DummyCXXFile.cxx")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestForANSIStreamHeaders.cxx")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestForAnsiForScope.cxx")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestForSSTREAM.cxx")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestForSTDNamespace.cxx")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeBuildSettings.cmake.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeCCompiler.cmake.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeCXXCompiler.cmake.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeConfigurableFile.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeFortranCompiler.cmake.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeJavaCompiler.cmake.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeRCCompiler.cmake.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeSystem.cmake.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CPack.Description.plist.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CPack.Info.plist.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckIncludeFile.c.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckIncludeFile.cxx.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckLibraryExists.lists.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckTypeSize.c.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/DartConfiguration.tcl.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/MacOSXBundleInfo.plist.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/NSIS.template.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/kde3init_dummy.cpp.in")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeTestGNU.c")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CMakeTestNMakeCLVersion.c")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckForPthreads.c")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckFunctionExists.c")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/CheckVariableExists.c")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/TestBigEndian.c")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/CMake/Modules" TYPE FILE FILES "/home/chris/cmake-2.3.4-20060317/Modules/readme.txt")
INCLUDE("/home/chris/cmake-2.3.4-20060317/Modules/Platform/cmake_install.cmake")

